
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YXItZ292LXBvc2FkYXM6d3N4cG9pNzU=

username=jmfragueiro&password=fito

###
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=jmfragueiro&password=fito

###
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=lschwegler&password=Damasco004

###
POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwOGQ0ZjExMS0xNDQzLTRlYWYtOTNlOS00MTlhNDUzMWFiYWIiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTU1MDAwMH0.e243dt-Jr676WmPPvdyawPS_UIhYPfhu19_KOmwR8---qvZAOnT9Fwh1dx-Byf7KLVcyQhn0tDoHnN2T3tSurA

{
    "name": "Juan Rodriguez",
    "email": "juan@acme.cl",
    "password": "Hunter2@3!",
    "phones": [
        {
        "number": "1234567",
        "citycode": "1",
        "contrycode": "57"
        }
    ]
 }

###
POST http://127.0.0.1:8080/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJhYjEzOTkxNC1iZDIzLTRkMTAtOGFmZS0xYjk3MTAyYWE4YTkiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTU1MDAwMH0.MPVe3OiMn4bqyCG41mvxPCQwQUipzqfvJvM0J4xal9EXoG5r28FJM4XK-vCHp_IIIowKInwtCWCaR4P2MnL9cg
