
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YXItZ292LXBvc2FkYXM6d3N4cG9pNzU=

username=jmfragueiro&password=fito

###
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=jmfragueiro&password=fito

###
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=lschwegler&password=Damasco004

###
GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJhYTQ0Mzg4Ny05NjllLTRiODMtYWI5YS1iZGU2YjU0Y2JlMWMiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTgwOTIwMH0.2ZWcbVfvRxwH_CZEzlBjgPS8P8jvtyeuDnU54ZD32nuD56pxf5pNasv2d2e2rNPoUFdv0FmpKpnAxnCXKRcmTg

###
GET http://127.0.0.1:8080/user/b3f2ebd3-4434-47b0-95ed-1a3f48825069
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJhYTQ0Mzg4Ny05NjllLTRiODMtYWI5YS1iZGU2YjU0Y2JlMWMiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTgwOTIwMH0.2ZWcbVfvRxwH_CZEzlBjgPS8P8jvtyeuDnU54ZD32nuD56pxf5pNasv2d2e2rNPoUFdv0FmpKpnAxnCXKRcmTg



###
POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJhYTQ0Mzg4Ny05NjllLTRiODMtYWI5YS1iZGU2YjU0Y2JlMWMiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTgwOTIwMH0.2ZWcbVfvRxwH_CZEzlBjgPS8P8jvtyeuDnU54ZD32nuD56pxf5pNasv2d2e2rNPoUFdv0FmpKpnAxnCXKRcmTg

{
    "name": "Juan Rodriguez",
    "email": "juan@acme.cl",
    "password": "Hunter2@3!",
    "phones": [
        {
        "number": "1234567",
        "citycode": "1",
        "contrycode": "57"
        }
    ]
 }

###
POST http://127.0.0.1:8080/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJhYTQ0Mzg4Ny05NjllLTRiODMtYWI5YS1iZGU2YjU0Y2JlMWMiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTgwOTIwMH0.2ZWcbVfvRxwH_CZEzlBjgPS8P8jvtyeuDnU54ZD32nuD56pxf5pNasv2d2e2rNPoUFdv0FmpKpnAxnCXKRcmTg
