
POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YXItZ292LXBvc2FkYXM6d3N4cG9pNzU=

username=jmfragueiro&password=fito

###

POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=jmfragueiro&password=fito

###

POST http://127.0.0.1:8080/auth/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Basic NDM1Zjk5NjgtZjY0My00N2U5LTlkMTU6MjNhNWNiMzYxYjFk

username=lschwegler&password=Damasco004

###

GET http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI1OThlYWUyNS0zMTM0LTQ3YzgtYTQ1ZS00ZjNlZWU4YjU5NGQiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NjcxNzAxNiwiZXhwIjoxNzQ2NzE3MTk2fQ.TiczSzKE6U15TDKwkP1-l_4mP3srqPsEWzTwVEUK-G_RYfUZIiowFGvnNtpQ27zTQKjkRhoKQ5iRthQC2Bp-9Q
###

GET http://127.0.0.1:8080/user/b3f2ebd3-4434-47b0-95ed-1a3f48825069
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiJkZDU5ODExMS0zMzMwLTQ2ZmQtOGJiYy01MzBiNTI0YThkY2UiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTk4MjAwMH0.lIdnQp872E021Hq11u3kkqCCfH9_iVIWnKZs28HqPHTv9GWAJ3klTF4ZFTaF_Gu0zC20R6qlY5zpE77u6k5D1Q

###
POST http://127.0.0.1:8080/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiIwMjFhZmRhOC1hOTUyLTQ2ODEtOWI0Ni1lOTVmZGNlM2M5NjEiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NTk4MjAwMH0.IWX-zkuHLZP8tHZpbc2lmQMDrUQRVcFZ2-F04f8KKX73l93wJtQz5LFOjmULli3J1wLGpqujh4fzs0glcHz5AQ

{
    "name": "Xua",
    "email": "xinxuauan22@acme.cl",
    "password": "Hunter2@3!",
    "phones": [
        {
        "number": "12345627",
        "citycode": "1",
        "contrycode": "57"
        }
    ]
 }

###

POST http://127.0.0.1:8080/auth/logout
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJraWQiOiJtYmVzciIsImFsZyI6IkhTNTEyIn0.eyJqdGkiOiI5ODFjMTNiZi00YjQyLTQzOGEtOTVlNi03ZjZhMTJiYmU2ODYiLCJzdWIiOiJqbWZyYWd1ZWlybyIsImlhdCI6MTc0NjU4NjgwMH0.Tv32FKZvqwJZWH7RZ12Z30R621EZuRCivT3q0FJRdBqqvOIWRfWw-StxUZMd1ZjBxlYBZPFXETClqMRexAVqog
